### ISSUE TITLE
Update publications of Prof. Hahn

### ISSUE THREAD

**Issue by benjamir** [JULIELab/web#12]

**Comment by t-duan** [comment]
What should be done concretely?

**Comment by benjamir** [comment]
Am 19. Juni 2018 20:23:46 MESZ, schrieb Tinghui Duan <notifications@github.com>:
>What should be done concretely?

It's just a reminder that Prof Hahn has to provide his top N publications in Core CL, DH and Biomedicine.
Next step is on him -- most recent reminder was today via mail.
--
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html
vox: +49 3641 9 44323 | fax: +49 3641 9 44321

**Comment by benjamir** [comment]
I received the best-of selection list. 20 DIN A4 pages... *shrug*

**Comment by t-duan** [comment]
Hopefully it's grouped after topics, at least...

**Comment by benjamir** [comment]
Main task done. Needs some cosmetic fixes -- layout, highlighting.
But I doubt anyone has enough time to do that for all the entries.
So I close the issue.
