### ISSUE TITLE
Directory structure coling_multimedia

### ISSUE THREAD

**Issue by kldtz** [JULIELab/web#13]
Currently coling_multimedia has a flat structure. I would prefer a structure similar to the previous one (e.g. teaching > ss18 > cl2 > blatt01.pdf). It's easier to maintain and navigate.

**Comment by t-duan** [comment]
I agree with you! @kldtz 
But before we do that, it's necessary to decide how it would look like. @benjamir

**Comment by benjamir** [comment]
I would ask the group to participate and not leave all of that to @eric24629 .
But @kldtz suggestion is a good starting point that should be implemented as a quasi-template.

**Comment by t-duan** [comment]
restructured
