### ISSUE TITLE
downloads redundant to coling_multimedia

### ISSUE THREAD

**Issue by benjamir** [JULIELab/web#14]
Honestly I don't understand why there is "downloads" and "coling_multimedia"

**Comment by t-duan** [comment]
I would like to have only /downloads. But then it old urls wouldn't work. We have to make a decision.

**Comment by benjamir** [comment]
On 21/06/18 10:57, Tinghui Duan wrote:
> I would like to have only /downloads. But then it old urls wouldn't work. We have to make a decision.

if the old site used /downloads and /coling_multimedia it's fine to keep
it during migration -- then just my fault that I overlooked it.

I support having only /downloads -- if your schedule is too tight, leave
it open as an enhancement and the whole group can improve that situation
incrementally.

**Comment by benjamir** [comment]
Ok, this is closely related to #3 and has become kind of redundant like the other URL related issues.
