### ISSUE TITLE
Redirections

### ISSUE THREAD

**Issue by chlor** [JULIELab/web#17]
We need redirections to all subdirectories.
https://julielab.de/Staff/Lohr/ is a redirection to https://julielab.de/Staff/Lohr/Christina+Lohr.html
but 
https://julielab.de/Staff/ (with ending /) shows a error page (404).

**Comment by kldtz** [comment]
This usually happens when a directory has no index.html file (which would be shown by default).

**Comment by benjamir** [comment]
fixed it already

**Comment by benjamir** [comment]
ee1e5ca36aa82dbe7a9fa015dfe2d2e301039e49

**Comment by benjamir** [comment]
Issues left are a duplicate of #3
